In [2]:
l = [2345,232,4332,23432,234]

In [3]:
l

[2345, 232, 4332, 23432, 234]

In [4]:
#in list we can have multiple types of data types

There are two types of arrays in python. 
- Python arrays
- Numpy arrays

We will be using numpy arrays in this tutorial

In [5]:
import numpy as np

In [6]:
#we cant have an array of different datatype

In [7]:
a = np.array(l)

In [8]:
a

array([ 2345,   232,  4332, 23432,   234])

In [9]:
b = np.array([12,232,232,43,"hello",True])

In [10]:
b

array(['12', '232', '232', '43', 'hello', 'True'], dtype='<U21')

In [11]:
l.pop()

234

In [12]:
l

[2345, 232, 4332, 23432]

1. inside arrays there are very strong methods and functions
2. We need arrays if we need to work on tables, data frame and the rest

## Slicing Arrays

In [13]:
a[2:]

array([ 4332, 23432,   234])

In [14]:
a

array([ 2345,   232,  4332, 23432,   234])

In [15]:
b = a[2:]

In [16]:
b[:] = 111

In [17]:
a

array([2345,  232,  111,  111,  111])

notice that any change to the copy of array affects the parent and vice versa. This is due to the fact that unlike lists, sliced array are merely an altered view of the parent array